# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Matthew Jordan
title: Matthew Jordan
email: matthewjordan@live.ca
description: Clean, clear, and under control since '94

url:  #matthewleejordan.com # the base hostname & protocol for your site
baseurl: #/al-folio # the subpath of your site, e.g. /blog/
last_updated: # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: mattyj612
twitter_username: mattyj612
linkedin_username: matthewleejordan
scholar_userid: sqbQNLgAAAAJ
instagram_username: mattyj612
goodreads_username: mattyj612

# google_analytics: UA-XXXXXXXXX # out your google-analytics code

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  projects:
    output: true
    permalink: /projects/:path/


# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
#blog_name: Matthew Jordan
#blog_description: Clean, clear, and under control since '94

# Pagination
#paginate: 4
#permalink: /posts/:year/:title/
#paginate_path: /posts/page:num/

#text:
#  pagination:
#    newer: 'Newer'
#    older: 'Older'

# Comments
disqus_shortname: Matthew Jordan # put your disqus shortname

# Optional features
show_social_icons:  true
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: rouge

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jekyll-scholar
    - jemoji

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"
